pipeline {
    agent any

    stages {
        stage('go version') {
            steps {
                bat 'go version'
            }
        }
        stage('node version') {
            steps {
                bat 'node --version'
            }
        }

    }
}
